# Generated by Django 5.1.1 on 2024-11-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MergeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('short_video_path', models.JSONField(blank=True, null=True)),
                ('large_video_paths', models.JSONField(blank=True, null=True)),
                ('video_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
