# Generated by Django 4.2.17 on 2025-01-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import merger.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merger', '0004_rename_progress_mergetask_total_frames_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergetask',
            name='large_video_paths',
        ),
        migrations.RemoveField(
            model_name='mergetask',
            name='short_video_path',
        ),
        migrations.RemoveField(
            model_name='mergetask',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='mergetask',
            name='video_links',
        ),
        migrations.AddField(
            model_name='mergetask',
            name='output_merged_video',
            field=models.FileField(blank=True, null=True, upload_to=merger.models.output_merger_video),
        ),
        migrations.AddField(
            model_name='mergetask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=merger.models.short_video_path)),
                ('merge_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_videos', to='merger.mergetask')),
            ],
        ),
        migrations.CreateModel(
            name='LargeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=merger.models.large_videos)),
                ('merge_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_videos', to='merger.mergetask')),
            ],
        ),
    ]
