# Generated by Django 4.2.17 on 2025-01-22 06:51

from django.db import migrations, models
import django.db.models.deletion
import merger.models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0005_remove_mergetask_large_video_paths_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, null=True, upload_to=merger.models.large_videos)),
                ('merge_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='merger.mergetask')),
            ],
        ),
    ]
