# Generated by Django 4.2.17 on 2025-01-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0006_videolinks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mergetask',
            name='output_merged_video',
        ),
    ]
