# Generated by Django 4.2.17 on 2025-01-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0008_alter_videolinks_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergetask',
            name='progress',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
