# Generated by Django 4.2.17 on 2025-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0009_mergetask_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergetask',
            name='percent_done',
            field=models.IntegerField(default=0),
        ),
    ]
