# Generated by Django 4.2.17 on 2025-01-23 14:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0010_mergetask_percent_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shortvideo',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
