# Generated by Django 4.2.17 on 2025-01-23 16:23

from django.db import migrations, models
import merger.models


class Migration(migrations.Migration):

    dependencies = [
        ('merger', '0011_alter_shortvideo_options_shortvideo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='largevideo',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=merger.models.large_video_processed),
        ),
        migrations.AddField(
            model_name='shortvideo',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to=merger.models.short_video_processed),
        ),
    ]
