# Generated by Django 5.1.1 on 2024-11-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='merge_credits',
        ),
        migrations.AddField(
            model_name='subscription',
            name='merge_credits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
