# Generated by Django 5.1.1 on 2024-11-02 08:35

import hooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hooks_content', models.FileField(blank=True, max_length=500, null=True, upload_to='hooks_videos/', validators=[hooks.models.validate_video_file])),
                ('google_sheets_link', models.URLField(blank=True, max_length=500, null=True)),
                ('eleven_labs_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('voice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('box_color', models.CharField(default='#485AFF', max_length=7)),
                ('font_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('task_id', models.CharField(max_length=1000, unique=True)),
                ('parallel_processing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('stripe_id', models.CharField(max_length=200)),
                ('video_limit', models.PositiveIntegerField()),
                ('price_per_video', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('video_links', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
