# Generated by Django 5.1.1 on 2024-11-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hook',
            name='dimension',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='option1', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='aspect_ratio',
            field=models.CharField(default='option1', max_length=255),
        ),
    ]
