# Generated by Django 4.2.17 on 2025-01-21 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hooks', '0004_alter_hook_hooks_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hook',
            name='dimension',
        ),
        migrations.RemoveField(
            model_name='hook',
            name='parallel_processing',
        ),
        migrations.RemoveField(
            model_name='hook',
            name='task_id',
        ),
        migrations.AddField(
            model_name='hook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
