# Generated by Django 4.2.17 on 2025-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hooks', '0006_hookvideolink_delete_task_hook_dimension_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.AddField(
            model_name='hook',
            name='progress',
            field=models.CharField(blank=True, default='0', max_length=50, null=True),
        ),
    ]
